import type { Metadata } from "next";
import { Inter,Poppins, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";
import Footer from "@/components/common/Footer";
const poppins = Poppins({
  subsets: ["latin"],
  weight: "300",
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: '300'
}) 
const inter = Inter ({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Brandora Design and Media Services",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
